<?php
// Automatically Generated by TestLink Installer - Mon, 11 Jan 16 08:45:59 +0100
define('DB_TYPE', 'mysql');
define('DB_USER', 'testlink');
define('DB_PASS', 'testlink');
define('DB_HOST', 'localhost');
define('DB_NAME', 'testlink');
define('DB_TABLE_PREFIX', '');
